name: Main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Set up paths
      run: |
        echo "GOPATH=$RUNNER_TEMP/go" >> $GITHUB_ENV
        echo "PATH=$PATH:$RUNNER_TEMP/go/bin" >> $GITHUB_ENV
    - name: Get govendor
      run: go get -u -v github.com/kardianos/govendor
    - name: Link source
      run: |
        mkdir -p $GOPATH/src/github.com/stripe
        ln -s $GITHUB_WORKSPACE $GOPATH/src/github.com/stripe/goforit
    - name: Run tests
      run: |
        cd $GOPATH/src/github.com/stripe/goforit 
        govendor test -v -timeout 10s +local
