name: Main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Set up GOPATH
      run: echo "GOPATH=$RUNNER_TEMP/go" >> $GITHUB_ENV
    - name: Get govendor
      run: go get -u -v github.com/kardianos/govendor
    - name: Setup source
      run: ln -s $(pwd) /go/src/github.com/stripe/goforit
    - name: Test
      run: govendor test -v -timeout 10s +local
      working-directory: /go/src/github.com/stripe/goforit
